networks:
  default: studionet
  studionet:
    id: 61999
    url: https://studio.genlayer.com/api
    chain_type: studionet
paths:
  contracts: contracts
  artifacts: artifacts
environment: studionet
